---
title: "Hypothesis Test"
author: "Mityl Biswas"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Hypothesis Testing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
```{r}
# Importing required packages
require(mvtnorm)
require(Package1)
n <- 100 # Number of individuals
m <- 11 # Number of time points
t <- seq(0, 1, length = m) # The time points
q <- 3 # Dimension of scalar covariate
data <- NULL # This will be our data frame
data$X <- t(rmvnorm(n,,diag(q))) # Scalar covariate of interest
data$Z <- t(as.matrix(rnorm(n))) # Nuisance covariates
m.i <- ceiling(runif(n,5,8)) # Getting number of time points for each individual
Y.star <- sin(2*pi*t) %*% data$Z + kronecker(t(exp(-colMeans(data$X))/2),t) + matrix(rnorm(n*m), m) # Generating densely sampled functional response 
data$Y <- NULL 
index <- NULL
data$t <- NULL
for(i in 1:n) 
{
    index[[i]] <- sort(sample(seq(1:m), m.i[i]), decreasing = FALSE)
    data$t[[i]] <- t[index[[i]]] # Sparsely sampled time points
    data$Y[[i]] <- Y.star[index[[i]],i] # Sparsely sampled response

}
p.val <- p_val(data) # Calling our function to compute p-value
p.val # Displaying p-value

```

----
